### ISSUE TITLE
Zenika logo - change all images with the new logo

### ISSUE THREAD

**Issue by jeanphibaconnais** [zenika-open-source/my-zenikanard#59]

**Comment by david-dasilva** [comment]
Je pense que cette issue est terminée via ton commit  https://github.com/zenika-open-source/my-zenikanard/commit/9e70838ce4f397ecf9b63e891f528176ce3239f2

**Comment by jeanphibaconnais** [comment]
Effectivement ! merci du ping @david-dasilva  😄
